const data = [
    {
      id: '1',
      name: 'Väinö Perko',
      age: 21,
      image: 'https://randomuser.me/api/portraits/men/13.jpg',
      email: 'vaino.perko@example.com',
    },
    {
      id: '2',
      name: 'Mihailo Jović',
      age: 47,
      image: 'https://randomuser.me/api/portraits/men/55.jpg',
      email: 'mihailo.jovic@example.com',
    },
    {
      id: '3',
      name: 'Nooa Harju',
      age: 57,
      image: 'https://randomuser.me/api/portraits/men/46.jpg',
      email: 'nooa.harju@example.com',
    },
    {
      id: '4',
      name: 'Ivan Medina',
      age: 27,
      image: 'https://randomuser.me/api/portraits/men/36.jpg',
      email: 'ivan.medina@example.com',
    },
    {
      id: '5',
      name: 'Tracey Hoffman',
      age: 69,
      image: 'https://randomuser.me/api/portraits/women/80.jpg',
      email: 'tracey.hoffman@example.com',
    },
    {
      id: '6',
      name: 'Emily Cunningham',
      age: 64,
      image: 'https://randomuser.me/api/portraits/women/50.jpg',
      email: 'emily.cunningham@example.com',
    },
    {
      id: '7',
      name: 'William Claire',
      age: 62,
      image: 'https://randomuser.me/api/portraits/men/57.jpg',
      email: 'william.claire@example.com',
    },
    {
      id: '8',
      name: 'Diane Martinez',
      age: 30,
      image: 'https://randomuser.me/api/portraits/women/51.jpg',
      email: 'diane.martinez@example.com',
    },
    {
      id: '9',
      name: 'Elif Tokatlıoğlu',
      age: 36,
      image: 'https://randomuser.me/api/portraits/women/4.jpg',
      email: 'elif.tokatlioglu@example.com',
    },
    {
      id: '10',
      name: 'Heather Byrd',
      age: 37,
      image: 'https://randomuser.me/api/portraits/women/71.jpg',
      email: 'heather.byrd@example.com',
    },
    {
      id: '11',
      name: 'Maya Williams',
      age: 29,
      image: 'https://randomuser.me/api/portraits/women/40.jpg',
      email: 'maya.williams@example.com',
    },
    {
      id: '12',
      name: 'Luukas Manni',
      age: 34,
      image: 'https://randomuser.me/api/portraits/men/40.jpg',
      email: 'luukas.manni@example.com',
    },
    {
      id: '13',
      name: 'Samir Karssen',
      age: 62,
      image: 'https://randomuser.me/api/portraits/men/82.jpg',
      email: 'samir.karssen@example.com',
    },
    {
      id: '14',
      name: 'Tracy Reid',
      age: 22,
      image: 'https://randomuser.me/api/portraits/men/97.jpg',
      email: 'tracy.reid@example.com',
    },
    {
      id: '15',
      name: 'Jacob Neal',
      age: 57,
      image: 'https://randomuser.me/api/portraits/men/58.jpg',
      email: 'jacob.neal@example.com',
    },
    {
      id: '16',
      name: 'درسا كامياران',
      age: 27,
      image: 'https://randomuser.me/api/portraits/women/96.jpg',
      email: 'drs.kmyrn@example.com',
    },
    {
      id: '17',
      name: 'Zhozefina Ohrimovich',
      age: 54,
      image: 'https://randomuser.me/api/portraits/women/58.jpg',
      email: 'zhozefina.ohrimovich@example.com',
    },
    {
      id: '18',
      name: 'Victoria Butler',
      age: 62,
      image: 'https://randomuser.me/api/portraits/women/17.jpg',
      email: 'victoria.butler@example.com',
    },
    {
      id: '19',
      name: 'Rich Clark',
      age: 51,
      image: 'https://randomuser.me/api/portraits/men/42.jpg',
      email: 'rich.clark@example.com',
    },
    {
      id: '20',
      name: 'Curtis Gibson',
      age: 28,
      image: 'https://randomuser.me/api/portraits/men/55.jpg',
      email: 'curtis.gibson@example.com',
    },
    {
      id: '21',
      name: 'Victoria Butler',
      age: 62,
      image: 'https://randomuser.me/api/portraits/women/17.jpg',
      email: 'victoria.butler@example.com',
    },
    {
      id: '22',
      name: 'Rich Clark',
      age: 51,
      image: 'https://randomuser.me/api/portraits/men/42.jpg',
      email: 'rich.clark@example.com',
    },
    {
      id: '23',
      name: 'Curtis Gibson',
      age: 28,
      image: 'https://randomuser.me/api/portraits/men/55.jpg',
      email: 'curtis.gibson@example.com',
    }
  ];
  
  export default data;
  